### ISSUE TITLE
Your solutions to Q4 and Q5 do not terminate exactly as the examples in the questions. 

### ISSUE THREAD

**Issue by zzhangbk** [svm96/3031_a3#4]
For example, in Question 5, when edge(a,b) exists in the graph, the result should be:
?- edge(a, b).
true.

NOT:
?- edge(a, b).
true;
false.

**Comment by svm96** [comment]
Yes, I had noticed that. But the false there only indicates that there are no more solutions, so that should be okay, no? 

(Ps. Thanks and out of curiosity, who are you amd how did you find this haha? :P Was really surprised to see this)

**Comment by zzhangbk** [comment]
Haha. You may refer to the message sent by TA from the inbox in canvas.

> Hi, Class,
> 
> This is a friendly reminder about the requirement in Assignment 3. To get full marks, your solutions should terminate exactly as the examples in the questions. 
> 
> For example, in Question 5, when edge(a,b) exists in the graph, the result should be:
> ?- edge(a, b).
> true.
> 
> NOT:
> ?- edge(a, b).
> true;
> false.
> 
> If you have further questions, please contact me via the email, or reach me at the Lab next Monday (Nov. 28).
> 
> Best regards.
> 
> Shuang

So I don't think the solution can get full marks. Actually I also encounter this problem when doing my assignment. Namely, edge(a, b) returns "true;false" rather than "true" and "degree(a, D) returns D=3;false" rather than "D=3", as specified in pdf.

**Comment by zzhangbk** [comment]
BTW, I find my way here by simply searching the repo, trying to find if there is someone else struggling on Q4 and Q5 like me. :-)

**Comment by svm96** [comment]
Ah, I see. Thanks for the heads up. Will have to look into it. Do let me know if you have any suggestions

**Comment by zzhangbk** [comment]
Okay, no problem. I've tried on using negations but failed. And also I think the examples on "parents of adam and eve" given by the professor (you can find them on Canvas ) might be useful. Good luck.

**Comment by zzhangbk** [comment]
Follow up: One of my friends has found that there is a built-in function in prolog named nonvar(X) that decides whether X is a variable or not (otherwise an atom). This completely solve the problem I mentioned earlier. You may have a try if you still do not work it out :-)

**Comment by svm96** [comment]
Ah, I solved it, don't worry. I forgot to commit and push, haha. I'm on mobile right now, will do it later. Thanks anyway!

**Comment by zzhangbk** [comment]
That's nice. Looking forward to your solutions :-)
